### ISSUE TITLE
Unknown module error after install extension

### ISSUE THREAD

**Issue by GeorgeXCV** [AckeeCZ/xk6-google-iap#5]
Can you help debug this?

Here is some of the workflow:
```
 - name: Build xk6 extensions
        id: xk6-extensions
        uses: szkiba/xk6bundler@v0
        with:
          platform: linux/amd64 windows/amd64
          with: |
            github.com/AckeeCZ/xk6-google-iap@latest  

      - name: Run load test
        uses: grafana/k6-action@v0.3.0
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SA_KEY: ${{ secrets.SA_KEY }}
        with:
          filename: tests/unauthenticated-users.js
          flags: --http-debug="${{ github.event.inputs.logging }}" 	
          cloud: false
```

I get this error:
`time="2023-08-18T02:12:35Z" level=error msg="GoError: unknown module: k6/x/googleIap\n\tat go.k6.io/k6/js.(*requireImpl).require-fm (native)\n\tat file:///github/workspace/tests/unauthenticated-users.js:4:0(42)\n" hint="script exception"`

I'm using the import statement from the example:
`import googleIap from 'k6/x/googleIap';`
